module.exports = {
  USER_NOT_FOUND: 'User not found',
  USER_INACTIVE: 'User is inactive',
  USER_EMPTY: 'User cannot be empty',
  INACTIVE_USER: 'Inactive user',
  INVALID_REQUEST: 'Invalid request',
  EMAIL_EMPTY: 'Email cannot be empty',
  RECORD_NOT_FOUND: 'Record not found',
  EMAIL_ALREADY_EXIST: 'Email already exists',
  INVALID_CREDENTIALS: 'Invalid credentials',
  AUTHENTICATION_FAILED: 'Failed to authenticate user',
  ERROR_IN_USER_CREATE: 'Error in create user action',
  ERROR_IN_PASSWORD_SETUP: 'Error in setting up user password',
  PASSWORD_EMPTY: 'Password cannot be empty',
  ERROR_IN_SECURE_CODE_CREATION: 'Error while creating secure code entry',
  ERROR_IN_FETCHING_SECURE_CODE: 'Error in retrieving secure code record',
  ERROR_IN_DELETING_SECURE_CODE: 'Error in deleting secure code record',
  NO_PASSCODE_FOUND_FOR_USER: 'No activation code found for the user',
  ACTIVATION_CODE_EMPTY: 'User activation code cannot be empty',
  ERROR_IN_SETUP_USER_PASSWORD: 'Error in user account password setup',
  ERROR_IN_AUTH_VALIDATION: 'Error in validating user credentials',
  ERROR_IN_AUTH_CODE_CREATION: 'Error in generating authentication code',
  ERROR_IN_AUTH_CODE_VALIDATION: 'Error in validating authentication code',
  ERROR_IN_AUTH_TOKEN_INVALIDATION: 'Error in invalidating user auth token',
  ERROR_IN_FETCHING_USER_LIST: 'Error while retrieving the users list',
  ERROR_IN_UPDATING_USER_DETAIL: 'Error while updating user detail',
  ERROR_IN_DELETING_USER_DETAIL: 'Error in deleting user detail',
  ERROR_IN_FETCHING_USER_DETAIL: 'Error while retrieving the user detail',
  ERROR_IN_FETCHING_USER_BY_EMAIL: 'Error while retrieving the user by email',
  INVALID_AUTHENTICATION_HEADER: 'Invalid authentication header value found in the request',
  ERROR_IN_SENDING_USER_ACTIVATION_EMAIL: 'Error in sending user activation code through email ',
  AUTHENTICATION_HEADER_REQUIRED: 'Required authentication header value not found in the request',
  NAME_ALREADY_EXISTS: 'Name already exists',
  ERROR_IN_FETCHING_RECORDS: 'Error in fetching records',
  // Role related error messages
  ROLE_NOT_FOUND: 'Role not found',
  ERROR_IN_FETCHING_ROLE_LIST: 'Error while retrieving the roles list',
  ERROR_IN_FETCHING_ROLE: 'Error while retrieving the role',
  ERROR_IN_DELETE_ROLE: 'Error during role delete operation',
  ERROR_IN_ROLE_CREATION: 'Error during role creation',
  SERVER_ERROR: 'Server error',
  NAME_EMPTY: 'Name cannot be empty',
  // Classroom related error messages
  INVALID_CLASSROOM_DATA: 'Invalid classroom data',
  ERROR_IN_CLASSROOM_CREATION: 'Error in classroom creation',
  ERROR_IN_FETCHING_CLASSROOM_LIST: 'Error in fetching classroom list',
  ERROR_IN_FETCHING_CLASSROOM: 'Error in fetching classroom',
  ERROR_IN_CLASSROOM_DELETE: 'Error in deleting classroom',
  ERROR_IN_CLASSROOM_UPDATE: 'Error in updating classroom',
  CLASSROOM_NOT_FOUND: 'Classroom not found',
  // Location related errors
  ID_EMPTY: 'Id cannot be empty',
  INVALID_TYPE_PINCODE: 'Pincode must be an integer',
  INVALID_PINCODE: 'Pincode must be between 4 and 6 digits',
  ERROR_IN_FETCHING_LOCATION: 'Error in fetching location detail',
  ERROR_IN_FETCHING_LOCATION_LIST: 'Error in fetching location list',
  ERROR_IN_UPDATE_LOCATION: 'Error in updating location detail',
  ERROR_IN_DELETE_LOCATION: 'Error in deleting location detail',
  LOCATION_NOT_FOUND: 'Location not found',
  ERROR_IN_LOCATION_CREATION: 'Error in location creation',
  // Accessories related errors
  ACCESSORY_NOT_FOUND: 'Accessories not found',
  ERROR_IN_ACCESSORY_CREATION: 'Error in accessory creation',
  ERROR_IN_FETCHING_ACCESSORIES_LIST: 'Error in fetching accessories list',
  ERROR_IN_FETCHING_ACCESSORY: 'Error in fetching accessory details',
  ERROR_IN_UPDATE_ACCESSORY: 'Error in updating accessory detail',
  ERROR_IN_DELETE_ACCESSORY: 'Error in deleting accessory detail',
  // Status related errors
  ERROR_IN_STATUS_CREATION: 'Error in status creation',
  ERROR_IN_FETCHING_STATUS_LIST: 'Error in fetching status list',
  STATUS_NOT_FOUND: 'Status not found',
  // models related messages
  NAME_MUST_BE_BETWEEN_3_AND_32_CHARACTERS: 'Name must be between 3 and 32 characters',
  NAME_MUST_ONLY_CONTAIN_ALPHABETIC_CHARACTERS: 'Name must only contain alphabetic characters',
  FIRST_NAME_MUST_BE_BETWEEN_3_AND_32_CHARACTERS: 'First name must be between 3 and 32 characters',
  FIRST_NAME_MUST_ONLY_CONTAIN_ALPHABETIC_CHARACTERS: 'First name must only contain alphabetic characters',
  LAST_NAME_MUST_BE_BETWEEN_3_AND_32_CHARACTERS: 'Last name must be between 3 and 32 characters',
  LAST_NAME_MUST_ONLY_CONTAIN_ALPHABETIC_CHARACTERS: 'Last name must only contain alphabetic characters',
  PHONE_NUMBER_MUST_CONTAIN_ONLY_NUMERIC_CHARACTERS: 'Phone number must contain only numeric characters',
  PHONE_NUMBER_MUST_BE_BETWEEN_10_CHARACTERS: 'Phone number must be between 10 characters',
  INVALID_EMAIL_ADDRESS: 'Invalid email address',
  ROLE_ID_MUST_BE_A_UUID: 'Role ID must be a UUID',
  LOCATION_ID_MUST_BE_A_UUID: 'Location ID must be a UUID',
  // Corporate related messages
  CORPORATE_NOT_FOUND: 'Corporate not found',
  ERROR_IN_CORPORATE_CREATION: 'Error in corporate creation',
  ERROR_IN_FETCHING_CORPORATE_LIST: 'Error in fetching corporate list',
  ERROR_IN_FETCHING_CORPORATE: 'Error in fetching corporate details',
  ERROR_IN_UPDATE_CORPORATE: 'Error in updating corporate detail',
  ERROR_IN_DELETE_CORPORATE: 'Error in deleting corporate detail'
};
